[theme]
primaryColor = "#10B981"
backgroundColor = "#090D16"
secondaryBackgroundColor = "#111827"
textColor = "#F9FAFB"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "warning"
